// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "27521206-e0cf-4bf8-91ad-916d27ed5368");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1742039948);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1742040328);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{d27b357b-cdc8-46b2-8e9d-7b4fbc700df7}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1742039945);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 152);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-rollout-in-the-old-sidebar:treatment-d");
user_pref("browser.newtabpage.activity-stream.discoverystream.locale-weather-config", "en-CA, en-GB, en-US, pt-BR, es-AR, es-CL, es-MX");
user_pref("browser.newtabpage.activity-stream.discoverystream.region-weather-config", "BR, AR, CL, CO, EC, MX, AU, NZ, ZA");
user_pref("browser.newtabpage.activity-stream.impressionId", "{4b4a9950-5eee-4ddd-9da7-79db58d16ba6}");
user_pref("browser.newtabpage.activity-stream.unifiedAds.spocs.enabled", true);
user_pref("browser.newtabpage.activity-stream.unifiedAds.tiles.enabled", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1742039946);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1742039948618");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1742061548618");
user_pref("browser.search.region", "BR");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250311232648");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20250311232648");
user_pref("browser.startup.homepage_override.mstone", "136.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1742040328);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1742040328);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":21,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("captchadetection.lastSubmission", 1742039);
user_pref("datareporting.dau.cachedUsageProfileID", "7dad2831-3367-4f02-b3d0-ba5ce5dd4712");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1742039946675");
user_pref("distribution.Garuda.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "136.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BR");
user_pref("dom.push.userAgentID", "389fd5a391e94f47891ee49861a30de9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECO5h1Gsw3CkzBAhScX5EyhoT3g==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250311232648");
user_pref("extensions.lastAppVersion", "136.0.1");
user_pref("extensions.lastPlatformVersion", "136.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"fe24392d-9f64-4b27-804d-20dacebc3379\",\"pictureinpicture@mozilla.org\":\"a98d9cff-f696-4e17-b768-446354d1ba95\",\"screenshots@mozilla.org\":\"ca4d58ae-2346-4942-bf33-1775b0b0e101\",\"webcompat-reporter@mozilla.org\":\"8696d645-c44a-4adf-9bee-60ae0f750076\",\"webcompat@mozilla.org\":\"9836f23e-65bc-4de3-ae70-b92e253760d5\",\"default-theme@mozilla.org\":\"62cfa8d9-3eb0-489b-80ef-a3640562562c\",\"addons-search-detection@mozilla.com\":\"44fbf08e-bfc4-425d-8b02-a0bd7a4abd85\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.pocketNewtab", "{\"slug\":\"hnt-weather-with-location-selector-non-eu-expansion-romance-and-germanic-lang\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"pocketNewtab\"},\"features\":null,\"firefoxLabsTitle\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"HNT weather with location selector non-EU expansion Romance and Germanic Lang\",\"userFacingDescription\":\"Providing weather widget on the newtab to more countries\",\"lastSeen\":\"2025-03-15T11:59:07.346Z\",\"featureIds\":[\"pocketNewtab\"],\"prefs\":[{\"name\":\"browser.newtabpage.activity-stream.discoverystream.locale-weather-config\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"localeWeatherConfig\",\"originalValue\":null},{\"name\":\"browser.newtabpage.activity-stream.discoverystream.region-weather-config\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"regionWeatherConfig\",\"originalValue\":null},{\"name\":\"browser.newtabpage.activity-stream.weather.locationSearchEnabled\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"weatherLocationSearch\",\"originalValue\":null}],\"isFirefoxLabsOptIn\":false,\"firefoxLabsTitle\":null,\"firefoxLabsDescription\":null,\"firefoxLabsGroup\":null,\"requiresRestart\":false,\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.localeWeatherConfig", "en-CA, en-GB, en-US, pt-BR, es-AR, es-CL, es-MX");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.regionWeatherConfig", "BR, AR, CL, CO, EC, MX, AU, NZ, ZA");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.weatherLocationSearch", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2025-03-15T11:59:07.295Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("sidebar.backupState", "{\"command\":\"\",\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECIoH4cPXQJVtBAgj6S8oxVDfbA==");
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1742040273);
user_pref("toolkit.telemetry.cachedClientID", "2a55fee7-7154-4ec0-aef9-c67c3d14d50c");
user_pref("toolkit.telemetry.cachedProfileGroupID", "7c3e64f9-bfbf-406b-b903-65948698ac9d");
user_pref("toolkit.telemetry.previousBuildID", "20250311232648");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
